name: Run MATLAB
on: [push]
jobs:
  my-job:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: R2023a
      - name: Run MATLAB command
        uses: matlab-actions/run-command@v2
        with:
          command: myfunc
